FROM quay.io/keycloak/keycloak:26.7.4
COPY --chown=keycloak:keycloak extension/target/keycloak-nats-durable-1.0.0-SNAPSHOT.jar /opt/keycloak/providers/nats-durable.jar
RUN /opt/keycloak/bin/kc.sh build --db=postgres
